#!/bin/bash

# Copyright 2016 Rafael Lorandi <coolparadox@gmail.com>
# This file is part of joymap, a framework for game controller
# button remapping for games built around jscal utility from
# Linux Console Project <http://sourceforge.net/projects/linuxconsole/>.
# 
# Joymap is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Joymap is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Concur. If not, see <http://www.gnu.org/licenses/>.

set -e

ME=$( basename $0 )
CFG_DIR=$( dirname $0 )

usage() {
	echo "usage: ${ME} [--scriptable] [--devices=/dev/input/jsN[,...]] [<game>]" 1>&2
	exit 1
}

SCRIPTABLE=0
declare -a DEVICES
while test $# -gt 0 ; do
	OPT="$1"
	case "$OPT" in
		--scriptable) SCRIPTABLE=1 ;;
		--devices=*)
			AUX=${OPT#*=}
			AUX=${AUX//,/ }
			DEVICES=( $AUX )
			;;
		-*) usage ;;
		*) break ;;
	esac
	shift
done
GAME=""
test $# -le 0 || {
	GAME="$1"
	shift
}
test $# -eq 0 || usage

message() {
	TYPE=$1
	shift
	if test $SCRIPTABLE -eq 0 ; then
		Xdialog --title "${ME} ${TYPE}" --msgbox "$*" 0 0 || true
	else
		echo "${ME} ${TYPE}:" "$*" 1>&2
	fi
}

info() {
	message info $*
}

warning() {
	message warning $*
}

fail() {
	message error $*
	exit 1
}

log_error_file() {
	LOG_FILE=$1
	shift
	if test $SCRIPTABLE -eq 0 ; then
		MSG_FILE=$( mktemp )
		echo "$*, log follows:" 1>>$MSG_FILE
		echo 1>>$MSG_FILE
		cat $LOG_FILE 1>>$MSG_FILE
		Xdialog --title "${ME} error" --no-cancel --textbox $MSG_FILE 20 80 || true
		rm -f $MSG_FILE
	else
		echo "${ME} error:" "$*, log follows:" 1>&2
		cat $LOG_FILE 1>&2
	fi
}

game_select_gui() {
	GAMES_FILE=$( mktemp )
	find $CFG_DIR/games -mindepth 1 -maxdepth 1 -type d -exec basename '{}' ';' 1>$GAMES_FILE
	local -a GAMES
	local IDX=0
	while read GAME ; do
		GAMES[IDX]=$GAME
		IDX=$((IDX+1))
		GAMES[IDX]=$GAME
		IDX=$((IDX+1))
	done 0<$GAMES_FILE
	rm -f $GAMES_FILE
	Xdialog \
		--title "${ME} game selection" \
		--no-tags \
		--menu "Please select a map configuration:" \
		0 0 10 \
		${GAMES[*]} \
		2>&1
}

if test $SCRIPTABLE -eq 0 ; then
	test -n "$GAME" || GAME=$( game_select_gui ) || true
	test -n "$GAME" || exit 0
else
	test -n "$GAME" || fail "game parameter is required in scriptable mode"
fi

find_controller_def() {
	MATCH_VENDOR=$1
	MATCH_PRODUCT=$2
	find $CFG_DIR/controllers -mindepth 1 -maxdepth 1 -type d | \
	while read DIR ; do
		CONTROLLER=$( basename $DIR )
		STATE_FILE=$CFG_DIR/controllers/$CONTROLLER/jscal.state
		local VENDOR=''
		local PRODUCT=''
		eval $( grep -e '^VENDOR=' -e '^PRODUCT=' $STATE_FILE )
		test "$MATCH_VENDOR" = "$VENDOR" || continue
		test "$MATCH_PRODUCT" = "$PRODUCT" || continue
		echo $CONTROLLER
		break
	done
}

test -n "$DEVICES" || {
	DEVICES=( /dev/input/js* )
}
test "${DEVICES[0]}" != '/dev/input/js*' || DEVICES=()
test ${#DEVICES[*]} -gt 0 || fail "no joysticks found in /dev/input/js*"

for JS in ${DEVICES[*]} ; do

	VENDOR=''
	PRODUCT=''
	NAME=''
	eval $( udevadm info -a -n $JS | /usr/share/joystick/ident )
	test -n "$VENDOR" -a -n "$PRODUCT" || continue
	info "Found $JS $VENDOR:$PRODUCT $NAME"
	CONTROLLER=$( find_controller_def $VENDOR $PRODUCT )
	test -n "$CONTROLLER" || {
		warning "jscal.state not found for '$VENDOR':'$PRODUCT', skipping"
		continue
	}
	#info "$VENDOR:$PRODUCT matches definition for controller: $CONTROLLER"

	BUTTONS_FILE="$CFG_DIR/controllers/$CONTROLLER/buttons"
	test -r "$BUTTONS_FILE" || fail "missing file: $BUTTONS_FILE"

	IDX=0
	declare -a BUTTON_NAMES
	declare -A NAME_INDEXES
	while read NAME ; do
		BUTTON_NAMES[IDX]=$NAME
		NAME_INDEXES[$NAME]=$IDX
		IDX=$((IDX+1))
	done 0<$BUTTONS_FILE
	#echo "button mapping for $CONTROLLER: ${BUTTON_NAMES[*]}" 1>&2
	#echo ${NAME_INDEXES[*]}

	STATE_FILE="$CFG_DIR/controllers/$CONTROLLER/jscal.state"
	test -r "$STATE_FILE" || fail "missing file: $STATE_FILE"

	TEMP_FILE=$( mktemp )
	sed -r \
		-e '/^jscal -u +/!d' \
		-e 's/^jscal -u *//' \
		-e 's/,/\n/g' \
		$STATE_FILE 1>$TEMP_FILE
	IDX=0
	declare -a AXIS_CODES
	declare -a BUTTON_CODES
	AXIS=1
	SIZE=0
	while read CODE ; do
		if test $AXIS -ne 0 ; then
			if test $SIZE -eq 0 ; then
				SIZE=$CODE
				IDX=0
			else
				if test $IDX -ge $SIZE ; then
					AXIS=0
					IDX=0
				else
					AXIS_CODES[IDX]=$CODE
					IDX=$((IDX+1))
				fi
			fi
		else
			BUTTON_CODES[IDX]=$CODE
			IDX=$((IDX+1))
		fi
	done 0<$TEMP_FILE
	rm -f $TEMP_FILE
	#echo "axis codes for $CONTROLLER: ${AXIS_CODES[*]}" 1>&2

	#echo -n "button codes for $CONTROLLER:" 1>&2
	#for NAME in ${BUTTON_NAMES[*]} ; do
		#IDX=${NAME_INDEXES[$NAME]}
		#CODE=${BUTTON_CODES[IDX]}
		#echo -n " $CODE($NAME)" 1>&2
	#done
	#echo 1>&2

	REMAP_FILE="$CFG_DIR/games/$GAME/${CONTROLLER}.buttons"
	test -r "$REMAP_FILE" || fail "missing file: $REMAP_FILE"
	declare -a REMAP_CODES
	REMAP_IDX=0
	while read NAME ; do
		IDX=${NAME_INDEXES[$NAME]}
		CODE=${BUTTON_CODES[IDX]}
		REMAP_CODES[REMAP_IDX]=$CODE
		REMAP_IDX=$((REMAP_IDX+1))
	done 0<$REMAP_FILE
	while test $REMAP_IDX -lt ${#BUTTON_CODES[*]} ; do
		REMAP_CODES[REMAP_IDX]=${BUTTON_CODES[REMAP_IDX]}
		REMAP_IDX=$((REMAP_IDX+1))
	done

	#info "applying $GAME button remap for $CONTROLLER..."
	COMMAND=$(
		IFS=','
		echo -n 'jscal -u'
		echo -n " ${#AXIS_CODES[*]},"
		echo -n "${AXIS_CODES[*]}"
		echo -n ",${#REMAP_CODES[*]},"
		echo -n "${REMAP_CODES[*]}"
		echo " $JS"
	)
	LOG_FILE=$( mktemp )
	echo $COMMAND 1>>$LOG_FILE
	if $COMMAND 1>>$LOG_FILE 2>&1 ; then
		info "$GAME remapping successfully applied to $CONTROLLER controller $JS"
	else
		log_error_file $LOG_FILE "$GAME remapping failed to $CONTROLLER controller $JS"
	fi
	rm -f $LOG_FILE

done

